In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [2]:
#### 2. Print the numpy version and the configuration (★☆☆)
print(np.version)
print(np.__config__)

<module 'numpy.version' from '/opt/miniconda3/envs/prep/lib/python3.12/site-packages/numpy/version.py'>
<module 'numpy.__config__' from '/opt/miniconda3/envs/prep/lib/python3.12/site-packages/numpy/__config__.py'>


In [6]:
#### 3. Create a null vector of size 10 (★☆☆)
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#### 4. How to find the memory size of any array (★☆☆)
print(a.nbytes)
print(a.size*a.itemsize)

80
80


In [8]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [10]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a = np.zeros(10,dtype=int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [12]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
a = np.arange(10,50,)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

In [24]:
#### 11. Create a 3x3 identity matrix (★☆☆)
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
rng = np.random.default_rng(seed = 50)
a = rng.random((3,3,3))
a

array([[[0.78742269, 0.83366933, 0.54790446],
        [0.9734491 , 0.23683356, 0.64692334],
        [0.06502607, 0.55557761, 0.40235748]],

       [[0.2659658 , 0.9866823 , 0.39731767],
        [0.32845619, 0.12515699, 0.1114578 ],
        [0.9845734 , 0.57893953, 0.8920926 ]],

       [[0.01508018, 0.59969868, 0.42022393],
        [0.37373088, 0.7065091 , 0.0614081 ],
        [0.23580973, 0.24576246, 0.44861055]]])

In [28]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
rng = np.random.default_rng(seed = 50)
a = rng.random((10,10))
print(np.min(a))
print(np.max(a))

0.0035814243756788766
0.9877969713943124


In [30]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
rng = np.random.default_rng(seed = 50)
a = rng.random(30)
print(np.mean(a))

0.4801050364166727


In [32]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
a = np.zeros((4,4))
a[0] = 1
a[-1] = 1
a[:,0] = 1
a[:,-1] = 1
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [33]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
a = np.ones((5,5))
a = np.pad(a, pad_width=1, mode='constant',constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [35]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(print(np.nan - np.nan))
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
None
True
False


In [36]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
a = np.diag([1,2,3,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [38]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))
None


In [42]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
pattern = [[0,1],
           [1,0]]
a = np.tile(pattern,(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [46]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
a = rng.random((5,5))
a = (a-a.min())/(a.max() - a.min())
a

array([[0.83462069, 0.74003537, 0.06221483, 0.16033229, 0.55428833],
       [0.848761  , 0.47767085, 0.60178599, 0.        , 0.19861041],
       [0.60641208, 0.10768175, 0.09569668, 0.09168599, 0.65026533],
       [1.        , 0.70831674, 0.17725829, 0.69150909, 0.54842686],
       [0.08218482, 0.25266183, 0.06810016, 0.21595986, 0.33399415]])

In [48]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color = np.dtype(
    [
        ("R",np.uint8),
        ("G",np.uint8),
        ("B",np.uint8),
        ("A",np.uint8)
    ]
)

a = np.array([
    (255, 0,   0,   255),   # Red
    (0,   255, 0,   255),   # Green
    (0,   0,   255, 255)    # Blue
],dtype=color)
print(a)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


In [55]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
c = a @ b
print(c)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [59]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
a = np.arange(12)
a[(a>3)&(a<8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

In [ ]:
#### 26. What is the output of the following script? (★☆☆)
print(sum(range(5),-1)) ## for python sum(iterable,startvalue)
from numpy import *
print(sum(range(5),-1)) ## for numpy sum(iterable,axis)

9
10


In [ ]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
"""
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
"""

# all are valid but last one raises ValueError for for numpy arrays

In [61]:
#### 28. What are the result of the following expressions? (★☆☆)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/r9/gms5rr7n331306rfv3b3kccc0000gn/T/ipykernel_57881/2616014464.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/r9/gms5rr7n331306rfv3b3kccc0000gn/T/ipykernel_57881/2616014464.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/r9/gms5rr7n331306rfv3b3kccc0000gn/T/ipykernel_57881/2616014464.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [63]:
#### 29. How to round away from zero a float array ? (★☆☆)
a = np.array([-2.7, -1.2, -0.1, 0.1, 1.2, 2.7])
a = np.copysign(np.ceil(np.abs(a)),a)
a

array([-3., -2., -1.,  1.,  2.,  3.])

In [69]:
#### 30. How to find common values between two arrays? (★☆☆)
a = np.arange(4).reshape(4,)
b = np.arange(12).reshape(3,4)
print(np.where(a==b))
print(a[np.isin(a,b)])
print(np.intersect1d(a,b))

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
[0 1 2 3]
[0 1 2 3]


In [71]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [72]:
#### 32. Is the following expressions true? (★☆☆)
"""
np.sqrt(-1) == np.emath.sqrt(-1)
"""
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1)==np.emath.sqrt(-1))
print(np.sqrt(-1+0j))
print(np.sqrt(-1+0j)==np.emath.sqrt(-1))

nan
1j
False
1j
True


In [73]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tomorrow)

2026-08-17
2026-08-18
2026-08-19


In [74]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [79]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
a = np.arange(5,dtype=float)
b = np.arange(5,dtype=float)
np.add(a,b,out=b)
np.divide(a,-2,out=a)
np.multiply(a,b,out=a)
print(a)

[ -0.  -1.  -4.  -9. -16.]


In [82]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

rng = np.random.default_rng()
a = rng.random(10) * 10
a.astype(int)
np.trunc(a).astype(int)
np.floor(a).astype(int)
a//1

array([2., 6., 9., 7., 8., 9., 8., 4., 9., 7.])

In [84]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
a = np.arange(5).reshape(5,1)
a = np.broadcast_to(a,(5,5))
a

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [85]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generator():
    for i in range(10):
        yield i*1
a = np.fromiter(generator(),dtype=int)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
a = np.linspace(0,1,12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [89]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
a = rng.random(10)
a.sort()
a

array([0.05305205, 0.3931263 , 0.56853601, 0.64162407, 0.68224322,
       0.76731712, 0.88110854, 0.90283495, 0.94690921, 0.95822482])