In [1]:
import numpy as np

In [5]:
a = np.arange(24).reshape(4,6)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a[2])
print(a[:,3])
print(a[2:,4:])
print(a[:,::2])
print(a[::-1,:])

(4, 6)
2
24
int64
[12 13 14 15 16 17]
[ 3  9 15 21]
[[16 17]
 [22 23]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]
[[18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [7]:
print(np.shares_memory(a[a%2==0],a))
print(np.shares_memory(a[::2],a))

False
True


In [8]:
c = np.arange(1,6)[:,None] * np.arange(1,6)
print(c)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [21]:
import time
start_time_py = time.perf_counter()
sum = 0
for i in range(1,10**6):
    sum+=i**2
end_time_py = time.perf_counter()

pytime = end_time_py-start_time_py

start_time_vec = time.perf_counter()
x = np.arange(1,10**6)
x = x**2
end_time_vec = time.perf_counter()

vectime = end_time_vec-start_time_vec

print(f"Python time: {pytime}")
print(f"Vec time: {vectime}")
print(f"Pytime/Vectime : {pytime/vectime}")

Python time: 0.10218195800553076
Vec time: 0.0017502499977126718
Pytime/Vectime : 58.381350172299996
